// Generated by gencpp from file communication_model/MotionCommand.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MODEL_MESSAGE_MOTIONCOMMAND_H
#define COMMUNICATION_MODEL_MESSAGE_MOTIONCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication_model
{
template <class ContainerAllocator>
struct MotionCommand_
{
  typedef MotionCommand_<ContainerAllocator> Type;

  MotionCommand_()
    : source()
    , linear_speed(0.0)
    , angular_speed(0.0)
    , acceleration(0.0)
    , deceleration(0.0)
    , enable_motion(false)  {
    }
  MotionCommand_(const ContainerAllocator& _alloc)
    : source(_alloc)
    , linear_speed(0.0)
    , angular_speed(0.0)
    , acceleration(0.0)
    , deceleration(0.0)
    , enable_motion(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_type;
  _source_type source;

   typedef float _linear_speed_type;
  _linear_speed_type linear_speed;

   typedef float _angular_speed_type;
  _angular_speed_type angular_speed;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef float _deceleration_type;
  _deceleration_type deceleration;

   typedef uint8_t _enable_motion_type;
  _enable_motion_type enable_motion;





  typedef boost::shared_ptr< ::communication_model::MotionCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication_model::MotionCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotionCommand_

typedef ::communication_model::MotionCommand_<std::allocator<void> > MotionCommand;

typedef boost::shared_ptr< ::communication_model::MotionCommand > MotionCommandPtr;
typedef boost::shared_ptr< ::communication_model::MotionCommand const> MotionCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication_model::MotionCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication_model::MotionCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication_model::MotionCommand_<ContainerAllocator1> & lhs, const ::communication_model::MotionCommand_<ContainerAllocator2> & rhs)
{
  return lhs.source == rhs.source &&
    lhs.linear_speed == rhs.linear_speed &&
    lhs.angular_speed == rhs.angular_speed &&
    lhs.acceleration == rhs.acceleration &&
    lhs.deceleration == rhs.deceleration &&
    lhs.enable_motion == rhs.enable_motion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication_model::MotionCommand_<ContainerAllocator1> & lhs, const ::communication_model::MotionCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication_model

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::communication_model::MotionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_model::MotionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_model::MotionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_model::MotionCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_model::MotionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_model::MotionCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication_model::MotionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bfb8733eb8119d340ffa42ca50b6814";
  }

  static const char* value(const ::communication_model::MotionCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bfb8733eb8119d3ULL;
  static const uint64_t static_value2 = 0x40ffa42ca50b6814ULL;
};

template<class ContainerAllocator>
struct DataType< ::communication_model::MotionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication_model/MotionCommand";
  }

  static const char* value(const ::communication_model::MotionCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication_model::MotionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string source        # who sent this message\n"
"float32 linear_speed\n"
"float32 angular_speed\n"
"float32 acceleration\n"
"float32 deceleration\n"
"bool    enable_motion\n"
;
  }

  static const char* value(const ::communication_model::MotionCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication_model::MotionCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source);
      stream.next(m.linear_speed);
      stream.next(m.angular_speed);
      stream.next(m.acceleration);
      stream.next(m.deceleration);
      stream.next(m.enable_motion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication_model::MotionCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication_model::MotionCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_speed: ";
    Printer<float>::stream(s, indent + "  ", v.linear_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_speed: ";
    Printer<float>::stream(s, indent + "  ", v.angular_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "deceleration: ";
    Printer<float>::stream(s, indent + "  ", v.deceleration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enable_motion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_motion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_MODEL_MESSAGE_MOTIONCOMMAND_H
